version: "3.8"

services:
  redis:
    image: docker.io/library/redis:alpine
    command: redis-server --requirepass ${REDIS_PASS:?redis password required} --save 60 1 --loglevel warning
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASS ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASS:?redis password required}
      REDIS_USER: ${REDIS_USER:-redis}
    env_file:
      - .env

volumes:
  redis:
